#:kivy 1.0

# NOTA: La clase que hereda de App tiene que tener el mismo nombre que el layout del 
# archivo .kv.
#:import const constantes
#:import Window kivy.core.window


<PropsFallaConfirmadaScreen>:
	# Los dropdowns para los tipos de falla se cargan de forma dinamica 

	ScrollView:
		id: main_scroll_view
		size_hint: (1, None)
		size: (root.width, root.height)
		#size: (800, 600)
		#size: (Window.width, Window.height)
		
		
