#:kivy 1.0

# NOTA: La clase que hereda de App tiene que tener el mismo nombre que el layout del 
# archivo .kv.
#:import const constantes

<PropsFallaConfirmadaScreen>:
	# Los dropdowns para los tipos de falla se cargan de forma dinamica 
	
	GridLayout:
		id: layout_principal
		cols:1
		rows:8
		#rows:7
		size_hint: (1,1)
		orientation: 'vertical'
		
		#canvas.before:
		#	Color:
		#		rgba: const.COLOR_LABELS_RGBA
		#	Rectangle:
		#		pos: self.pos
		#		size: self.size


		
