#:kivy 1.0

# NOTA: La clase que hereda de App tiene que tener el mismo nombre que el layout del 
# archivo .kv.

<PropsFallaConfirmadaScreen>:
	# Los dropdowns para los tipos de falla se cargan de forma dinamica 
	layout_principal: main_layout

	GridLayout:
		id: main_layout
		cols:1
		rows:8
		size_hint: (1,1)
		#rows:7
		orientation: 'vertical'
		canvas.before:
			Color:
				rgba: const.COLOR_LABELS_RGBA
			Rectangle:
				pos: self.pos
				size: self.size
		
